// Code generated by protoc-gen-go. DO NOT EDIT.
// source: router.proto

package router

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetParameter struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParameter) Reset()         { *m = GetParameter{} }
func (m *GetParameter) String() string { return proto.CompactTextString(m) }
func (*GetParameter) ProtoMessage()    {}
func (*GetParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{0}
}

func (m *GetParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParameter.Unmarshal(m, b)
}
func (m *GetParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParameter.Marshal(b, m, deterministic)
}
func (m *GetParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParameter.Merge(m, src)
}
func (m *GetParameter) XXX_Size() int {
	return xxx_messageInfo_GetParameter.Size(m)
}
func (m *GetParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParameter.DiscardUnknown(m)
}

var xxx_messageInfo_GetParameter proto.InternalMessageInfo

func (m *GetParameter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetParameter struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetParameter) Reset()         { *m = SetParameter{} }
func (m *SetParameter) String() string { return proto.CompactTextString(m) }
func (*SetParameter) ProtoMessage()    {}
func (*SetParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{2}
}

func (m *SetParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetParameter.Unmarshal(m, b)
}
func (m *SetParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetParameter.Marshal(b, m, deterministic)
}
func (m *SetParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetParameter.Merge(m, src)
}
func (m *SetParameter) XXX_Size() int {
	return xxx_messageInfo_SetParameter.Size(m)
}
func (m *SetParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_SetParameter.DiscardUnknown(m)
}

var xxx_messageInfo_SetParameter proto.InternalMessageInfo

func (m *SetParameter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetParameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{3}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*GetParameter)(nil), "GetParameter")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*SetParameter)(nil), "SetParameter")
	proto.RegisterType((*SetResponse)(nil), "SetResponse")
}

func init() { proto.RegisterFile("router.proto", fileDescriptor_367072455c71aedc) }

var fileDescriptor_367072455c71aedc = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xca, 0x2f, 0x2d,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe0, 0xe2, 0x71, 0x4f, 0x2d, 0x09,
	0x48, 0x2c, 0x4a, 0xcc, 0x4d, 0x2d, 0x49, 0x2d, 0x12, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x94,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x94, 0xb9, 0xb8, 0xdd, 0x53, 0x4b, 0x82,
	0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53,
	0xa1, 0x4a, 0x20, 0x1c, 0x25, 0x33, 0x2e, 0x9e, 0x60, 0xbc, 0xc6, 0x20, 0xf4, 0x31, 0x21, 0xeb,
	0x53, 0xe5, 0xe2, 0x0e, 0x46, 0x32, 0x5c, 0x8c, 0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x04,
	0xac, 0x93, 0x23, 0x08, 0xca, 0x33, 0x0a, 0xe1, 0x62, 0x0b, 0x02, 0xbb, 0x5a, 0x48, 0x85, 0x8b,
	0xd9, 0x3d, 0xb5, 0x44, 0x88, 0x57, 0x0f, 0xd9, 0xd5, 0x52, 0x3c, 0x7a, 0x48, 0x4e, 0x54, 0x62,
	0x00, 0xa9, 0x0a, 0x06, 0xab, 0x0a, 0x46, 0x55, 0x15, 0x8c, 0xac, 0x2a, 0x89, 0x0d, 0x1c, 0x04,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xb1, 0xbf, 0xdb, 0x12, 0x01, 0x00, 0x00,
}
